Board page
NikitaKakurin/project-management-app pull request #27
Opened 2022-11-25 13:55 UTC by bycolour2

2022-11-25 15:50 UTC, NikitaKakurin requested changes
удалить таск не работает
не убрал добавление файла при создании таска
не закрывается модалка редактирования после редактирования
модалка редактирования поверх спинера
удалить столбец не работает
модалки добавить/редактировать таск, добавить столбец не резиновые, (адаптивные) при 320px

2022-11-26 13:16 UTC, NikitaKakurin requested changes
https://user-images.githubusercontent.com/28681971/204090844-a310cab7-1cf3-455e-8ac7-c3c2c187d9e9.mp4

добавь проверку наличия user в таске

2022-11-26 13:19 UTC, NikitaKakurin commented on src/components/Task.tsx
> -import { IFile, ITask } from 'models/dbTypes';
здесь лучше писать import type

2022-11-27 12:57 UTC, NikitaKakurin approved these changes

2022-11-28 13:46 UTC, NikitaKakurin commented on src/components/modals/AddColumnModalContent.tsx
> +                      characters.
добавь перевод

2022-11-28 13:47 UTC, NikitaKakurin commented on src/components/modals/AddColumnModalContent.tsx
>                      placeholder="Title..."
тоже перевод нужен

2022-11-28 13:53 UTC, lg0leg approved these changes

2022-11-28 15:21 UTC, NikitaKakurin approved these changes

2022-11-28 15:26 UTC, merged