Welcome
NikitaKakurin/project-management-app pull request #28
Opened 2022-11-26 17:08 UTC by lg0leg

Добавлена верстка для главной страницы
+1 библиотека, не забудьте обновить зависимости
![image](https://user-images.githubusercontent.com/79754202/204100460-6b7bbc18-e6ce-4fd1-ba51-41bc73c38c5e.png)

2022-11-27 12:55 UTC, NikitaKakurin approved these changes

2022-11-28 13:34 UTC, bycolour2 requested changes

2022-11-28 13:34 UTC, bycolour2 commented on src/pages/Welcome.tsx
> +            {lang == 'en' ? 'In a free course from ' : 'На бесплатных курсах от '}
On free courses from

2022-11-28 13:34 UTC, bycolour2 commented on src/pages/Welcome.tsx
> +              ? 'How can I learn to make apps that are as cool as they are?'
How to learn how to create such cool websites?
или 
How to learn how to create the same cool sites?

2022-11-28 13:34 UTC, bycolour2 commented on src/pages/Welcome.tsx
> +                    ? 'Created the project, set up the server side and interaction with it, added forms and authorization, organized the work of the team.'
Created the project, set up the server side and interaction with it, added forms and authorization, organized work of the team.

2022-11-28 13:34 UTC, bycolour2 commented on src/pages/Welcome.tsx
> +            {/* <ReactHookForm size={60} /> */}
Так задумано?

2022-11-28 13:37 UTC, lg0leg commented on src/pages/Welcome.tsx
> +            {/* <ReactHookForm size={60} /> */}
Ага, она смотрится не оч)

2022-11-28 13:54 UTC, bycolour2 approved these changes

2022-11-29 12:38 UTC, merged