Profile page
NikitaKakurin/project-management-app pull request #29
Opened 2022-11-27 12:53 UTC by NikitaKakurin

![image](https://user-images.githubusercontent.com/28681971/204136298-5b654e5d-79b2-4d0f-9ccc-6fac9eb6ec9f.png)

Add profile page
change validation in SignIn, SignUp

2022-11-28 13:35 UTC, lg0leg approved these changes

2022-11-28 14:47 UTC, bycolour2 requested changes

2022-11-28 14:47 UTC, bycolour2 commented on src/pages/Profile.tsx
> +          <h2 className="text-center text-lg font-medium">{`${user.name}(${user.login})`}</h2>
Добавь пробел между именем и логином

2022-11-28 14:47 UTC, bycolour2 commented on src/pages/Profile.tsx
> +            text={lang === LangKey.EN ? 'Delete User' : 'Удалить Пользователя'}
Пользователя не надо с большой букввы писать

2022-11-28 14:47 UTC, bycolour2 commented on src/pages/Profile.tsx
> +          <AuthInput
Может стоит изменить название компонента с AuthInput на FormInput и использовать его как общий стилевой компонент?

2022-11-28 14:47 UTC, bycolour2 commented on src/pages/SignUp.tsx
> +            placeholder={lang === LangKey.EN ? 'name' : 'имя'}
С большой буквы

2022-11-28 14:47 UTC, bycolour2 commented on src/pages/SignUp.tsx
> +            placeholder={lang === LangKey.EN ? 'login' : 'логин'}
С большой буквы

2022-11-28 14:47 UTC, bycolour2 commented on src/pages/SignIn.tsx
> +            placeholder={lang === LangKey.EN ? 'login' : 'логин'}
С большой буквы

2022-11-28 14:47 UTC, bycolour2 commented on src/pages/SignIn.tsx
> +            placeholder={lang === LangKey.EN ? 'password' : 'пароль'}
С большой буквы

2022-11-28 14:47 UTC, bycolour2 commented on src/pages/SignUp.tsx
> +            placeholder={lang === LangKey.EN ? 'password' : 'пароль'}
С большой буквы

2022-11-28 14:47 UTC, bycolour2 commented on src/utils/getAuthValidation.ts
> +    default:
Ошибки с больших букв

2022-11-28 14:47 UTC, bycolour2 commented on src/components/ProfileConfirmInput.tsx
> +  console.log(defaultValue);
??

2022-11-28 14:47 UTC, bycolour2 commented on src/pages/Profile.tsx
> +          <AuthSubmit text={lang === LangKey.EN ? 'Edit' : 'Редактировать'} />
Надо какой-то отклик при нажатии при пустых полях

2022-11-28 15:26 UTC, NikitaKakurin commented on src/pages/Profile.tsx
> +          <AuthInput
эти компоненты используются только в авторизации и странице профиля, и в принципе имеют одинаковые поля и валидацию, и под другие нужды не особо подойдут, поэтому я не думаю что стоит менять название

2022-11-28 15:32 UTC, bycolour2 commented on src/pages/Profile.tsx
> +          <AuthInput
Так суть в том, что можно сделать единый инпут компонент, валидацию туда можно объектом передать и соответственно вынести компонент ошибки отдельно, мне кажется так разумнее чем делать инут аус, инпут юзер, инпут таск, инпут ещё что-то, как и с другими мини элементами

2022-11-28 15:35 UTC, NikitaKakurin commented on src/pages/Profile.tsx
> +          <h2 className="text-center text-lg font-medium">{`${user.name}(${user.login})`}</h2>
добавлял, не смотрится

2022-11-28 15:35 UTC, NikitaKakurin commented on src/pages/Profile.tsx
> +            text={lang === LangKey.EN ? 'Delete User' : 'Удалить Пользователя'}
ок

2022-11-28 15:39 UTC, bycolour2 commented on src/pages/Profile.tsx
> +          <h2 className="text-center text-lg font-medium">{`${user.name}(${user.login})`}</h2>
Одно под другим, как у меня в поповере?

2022-11-28 15:39 UTC, NikitaKakurin commented on src/pages/Profile.tsx
> +          <AuthInput
да но это излишнее усложнение, тебе нужно будет писать сложные типы если ты будешь использовать в формах с разными полями,   
label: Path<IAuthRequest>;
register: UseFormRegister<IAuthRequest>;
  errors: Partial<
    FieldErrorsImpl<{
      name: string;
      login: string;
      password: string;
      passwordRepeat: string;
    }>
  >;
проще отельный компонет сделать

2022-11-28 15:41 UTC, bycolour2 commented on src/pages/Profile.tsx
> +          <AuthInput
Вообще думаю не будет, но да ладно не буду спорить, просто потом все стилистический проводить придется,Лан, разберемся

2022-11-28 15:44 UTC, NikitaKakurin commented on src/pages/Profile.tsx
> +          <h2 className="text-center text-lg font-medium">{`${user.name}(${user.login})`}</h2>
нет, просто Name(login) лучше смотрится чем Name (login).
если одно под другим и  так форма на весь экран а так будет еще больше.

2022-11-28 15:49 UTC, bycolour2 commented on src/pages/Profile.tsx
> +          <h2 className="text-center text-lg font-medium">{`${user.name}(${user.login})`}</h2>
Так может, надо профиль отдельно, а изменения профиля в модалке?

2022-11-28 15:54 UTC, NikitaKakurin commented on src/pages/Profile.tsx
> +          <h2 className="text-center text-lg font-medium">{`${user.name}(${user.login})`}</h2>
а что будет кроме кнопки редактировать профиль на странице профиля? и опять же я считаю что авторизация и профиль смежные странички должны быть оформлены одинаково

2022-11-28 16:35 UTC, bycolour2 commented on src/pages/Profile.tsx
> +          <h2 className="text-center text-lg font-medium">{`${user.name}(${user.login})`}</h2>
Кнопка удалить логин пароль, и типа аватарка
Считаю что в этом моменте ты не прав, они не должны быть одинаковые

2022-11-28 16:38 UTC, bycolour2 commented on src/pages/Profile.tsx
> +          <h2 className="text-center text-lg font-medium">{`${user.name}(${user.login})`}</h2>
Как минимум, изменить пароль должно быть нельзя

2022-11-28 16:48 UTC, NikitaKakurin commented on src/pages/Profile.tsx
> +          <h2 className="text-center text-lg font-medium">{`${user.name}(${user.login})`}</h2>
всмысле, пароль изменить нельзя? ты о чем?

2022-11-29 12:30 UTC, bycolour2 approved these changes

2022-11-29 13:25 UTC, merged